export const HELICOPTER = {
  SPEED: 22,
  VERT_SPEED: 14,
  ROT_SPEED: 2.0,
  DRAG: 3.5,
  ACCEL: 35,
  TILT_AMOUNT: 0.2,
  MAX_ALTITUDE: 80,
  MIN_ALTITUDE: 3,
  MAX_PASSENGERS: 3,
  START_INTEGRITY: 100,
  COLLISION_DAMAGE: 5,
  FIRE_DAMAGE: 3,
};

export const RESCUE = {
  HOVER_RADIUS: 6,
  RESCUE_TIME: 2.5,
  DROPOFF_RADIUS: 8,
  PROGRESS_DECAY: 2.0,
  MAX_ALT_DIFF: 8,
};

export const MISSION = {
  BURNING_BUILDING: {
    TIMER: 150,
    SURVIVORS: 5,
    FIRE_SPREAD_RATE: 0.1,
    SMOKE_THICKEN_RATE: 0.05,
  },
};

export const SCORING = {
  PER_SURVIVOR: 1000,
  TIME_BONUS_MULTIPLIER: 50,
  INTEGRITY_BONUS_MULTIPLIER: 20,
  PERFECT_RESCUE_BONUS: 500,
};

export const CAMERA = {
  OFFSET: { x: 0, y: 8, z: -18 },
  LERP_SPEED: 4,
  LOOK_AHEAD: 5,
};

export const WORLD = {
  BOUNDARY: 120,
  GROUND_SIZE: 400,
  FOG_DENSITY: 0.006,
};
